### ISSUE TITLE
imgcat has problems with `tmux`

### ISSUE THREAD

**Issue by gamefiend** [campoy/tools#11]
Hi! imgcat is really cool.  The only snag I found is that it doesn't work from within tmux.  Looking around I saw that the [iterm2 folks deal with this in their bash script version](https://raw.githubusercontent.com/gnachman/iTerm2/master/tests/imgcat):

```
# tmux requires unrecognized OSC sequences to be wrapped with DCS tmux;
# <sequence> ST, and for all ESCs in <sequence> to be replaced with ESC ESC. It
# only accepts ESC backslash for ST.
function print_osc() {
    if [[ $TERM == screen* ]] ; then
        printf "\033Ptmux;\033\033]"
    else
        printf "\033]"
    fi
}

# More of the tmux workaround described above.
function print_st() {
    if [[ $TERM == screen* ]] ; then
        printf "\a\033\\"
    else
        printf "\a"
    fi
}
```

I'd be happy to submit a PR to make this change if it seems OK to you!

**Comment by campoy** [comment]
happy to get a PR yeah! seems like the fix should be *quite* easy too

**Comment by gamefiend** [comment]
👍 sweet! working on it now!

**Comment by campoy** [comment]
PR merged! And only took me 2 years to notice

So sorry!
